# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_auto_20161028_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='photo',
            field=models.ImageField(upload_to='imovel/', verbose_name='foto'),
        ),
    ]
